version: '3'

services:
  db:
    container_name: network_postgres
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_data:/var/lib/postgresql/data/:rw
  web:
    container_name: network_web
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "80:8000"
    depends_on:
      - db
